[package]
name = "ocr_clipboard"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard    = "3.5"
image      = "0.25.6"
leptess    = "0.14"
tempfile   = "3.3"
copypasta  = "0.10.2"
win-msgbox = "0.2.1"
anyhow     = "1.0"
rfd = "0.15.3"
